class AhaServices::Slack < AhaService
  string :webhook_url,
    description: "Webhook URL from Slack, generated by creating an 'Incoming webhook'."
  install_button
  
  def receive_installed
    send_message(text: "Slack integration installed in <b>Aha!</b>")
  end
  
  def receive_audit
    audit = payload.audit
    user = if audit.user
        audit.user.name
      else
        "Aha!"
      end
    
    send_message(fallback: "#{user} #{audit.description}",
      pretext: "#{user} <#{audit.auditable_url}|#{audit.description}>",
      fields: audit.changes.collect do |change|
        {
          title: change.field_name,
          value: change.value,
          short: false
        }
      end)
  end
    
  
protected

  def send_message(message)
    http.headers['Content-Type'] = 'application/json'
    response = http_post(data.webhook_url, message.to_json)
    if [200, 201, 204].include?(response.status)
      return
    elsif response.status == 404
      raise AhaService::RemoteError, "URL is not recognized"
    else
      error = Hashie::Mash.new(JSON.parse(response.body))
      
      raise AhaService::RemoteError, "Unhandled error: STATUS=#{response.status} BODY=#{error.message}"
    end
  end
  
end