class AhaServices::Slack < AhaService
  caption "Send all activity from Aha! into group chat"
  
  string :webhook_url,
    description: "Webhook URL from Slack, generated by creating an 'Incoming webhook'."
  install_button
  
  def receive_installed
    send_message(text: "Aha! integration installed successfully. Make sure you enable the integration!")
  end
  
  def receive_audit
    audit = payload.audit
    return unless audit.interesting
    
    user = if audit.user
        audit.user.name
      else
        "Aha!"
      end
    
    link = if audit.auditable_url
        "<#{audit.auditable_url}|#{audit.description}>"
      else
        audit.description
      end
      
    send_message(fallback: "#{user} #{audit.description}",
      pretext: "#{user} #{link}",
      username: "Aha!",
      icon_url: "https://secure.aha.io/assets/logos/aha_square_300.png",
      fields: audit.changes.collect do |change|
        {
          title: change.field_name,
          value: html_to_plain(change.value),
          short: false
        }
      end)
  end
    
  
protected

  def send_message(message)
    http.headers['Content-Type'] = 'application/json'
    response = http_post(data.webhook_url, message.to_json)
    if [200, 201, 204].include?(response.status)
      return
    elsif response.status == 404
      raise AhaService::RemoteError, "URL is not recognized"
    else
      error = Hashie::Mash.new(JSON.parse(response.body))
      
      raise AhaService::RemoteError, "Unhandled error: STATUS=#{response.status} BODY=#{error.message}"
    end
  end
  
end